# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2ef7dc3f77627589b3c3076eb315d75981e8347594edb66831055c6e084c05d612ae484c7a4ea4bee977fe9f52b81fa1fe178377e599847a9ffd924f1ab088e9

test:
  secret_key_base: dcc31d291d51cc95be7e3ad7218051d024ec5adadab1de04cb1cd38d56b2dc5fbf3d3c37afb980197c53edd6d8683bed03188c2d22d204de4b7e9a7b9b8afcd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
